### ISSUE TITLE
Duplicate parser imports?

### ISSUE THREAD

**Issue by prmiller91** [chapinb/anparser#4]
What's the purpose of anparser/anparser/**init**.py? anparser.py seems to work regardless of if you place an import for a specific plugin in the **init**.py script or not. Are we unnecessarily making parser imports in both anparser/anparser/**init**.py and anparser/anparser/anparser.py?

**Comment by chapinb** [comment]
My understanding is that if someone wanted to call it as a library, the init allows for them to have all necessities imported by default. I have been yet to try this, though it could be tested by attempting an import and function call from a script in a different directory.
