### ISSUE TITLE
Writer's UnicodeEncodeError

### ISSUE THREAD

**Issue by prmiller91** [chapinb/anparser#6]
While I was working on the Google chrome parser I ran into the following error: 

![screen shot 2015-01-12 at 3 13 37 pm](https://cloud.githubusercontent.com/assets/9575133/5710239/69fe41c6-9a6e-11e4-8755-749ed0f26bc1.png)

  I assumed this was because I was messing around with webkit timestamps, but then I ignored all timestamps and still received the error. Looking at my output, the last entry in the android_chrome_history.csv is from the url table with id 21 - even though there are 32 entries in that database for the phone dataset.

   I then tried the tablet dataset, and also received a UnicodeEncodeError, but this time before it reached the Google chrome parser. 

![screen shot 2015-01-12 at 3 16 59 pm](https://cloud.githubusercontent.com/assets/9575133/5710289/e5369d7a-9a6e-11e4-9476-1569e7092a74.png)

**Comment by chapinb** [comment]
If possible, we should encode this data in the plugins to ensure that all output is written in a standard fashion. This is just so that if a future writer does not support UTF, it can still function.

**Comment by chapinb** [comment]
Is this now resolved in 903555c?

**Comment by prmiller91** [comment]
Yes, like you said above this is something we'll want to look into more going forwards to ensure stability.
