### ISSUE TITLE
tests.py failure as of 29b32ed402

### ISSUE THREAD

**Issue by chapinb** [chapinb/anparser#9]
Re-write tests to reflect the new method for handling sqlite

https://travis-ci.org/anparser/anparser/builds/48438647

![image](https://cloud.githubusercontent.com/assets/7152035/5949973/f8f03230-a721-11e4-9b99-0a4ecb313702.png)

**Comment by prmiller91** [comment]
Fixed in 586d9af5a0494f289d9d003accac0fb4aba820e5
